### ISSUE TITLE
remote folder not same as nextcloud server config

### ISSUE THREAD

**Issue by S74HK9hV** [PhieF/CarnetAndroid#40]
first of all, i just want to thank devs for this. finally have a real alternative to google keep! very excited for this project

steps:
- install carnet app on nextcloud server
- change data directory from "Documents/QuickNote" to "notes/quicknote"
- install android app
- set sync with cloud storage > other sync options > connect with nextcloud > connect with nextcloud app > select account
- sync doesn't work properly
- go to app setting "Remote Folder". app is pointing to "Documents/Quicknote"
- click on Remote Folder settings to change

result: app crashes

expected behaviour: 
1) app should automatically take the same data directory as configured in nextcloud
2) app should be able to change data directory without crash

carnet app: ver 0.1-20190210.2226
android 8.0.0
nextcloud server 15.0.4

**Comment by maxdrash** [comment]
In the lastest version of Carnet for Android, we could choose the path of the Quicknote folder.
For example: on my Nextcloud Server i choose to store the Quicknote files to .carnet/Quicknote (to hide these foler from the file browser) and i can't choose this option in the versions 0.12.8 of Carnet for Android anymore.

@S74HK9hV i haven't the "Remote Folder" option in settings for this version.

Thank you.

**Comment by maxdrash** [comment]
Hi.

Same for me, com.spisoft.quicknote v0.12.8.

**Comment by PhieF** [comment]
I've fixed the crash

The suggestion to retrieve the right folder will come later (carnet's android app doesn't require the nextcloud app to work, I will have to find a way to retrieve the folder when the app is detected)

**Comment by maxdrash** [comment]
This works great !
Thank you.

**Comment by BerndSy** [comment]
Hi, I upgraded to 0.13.0 from F-Droid but still cannot select the Nextcloud remote folder. The app shows the Documents/QuickNote folder although it does not exist. It allows me to pick the root folder / but it doesn't sync there. When I select another folder it restarts once and crashes after the second attempt.

Android 9 and LineageOS 15.1
Nextcloud 15.0.5

**Comment by koug44** [comment]
Same here without the crash
